services:
  - type: web
    name: spainrp-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: PUBLIC_BASE_URL
        fromService:
          type: web
          name: spainrp-frontend
          property: host
      - key: BOT_API_URL
        value: https://tu-bot.onrender.com
      - key: BOLSA_API_URL
        value: https://tu-bolsa.onrender.com
      - key: ECONOMIA_API_URL
        value: https://tu-economia.onrender.com
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        value: https://spainrp-web.onrender.com/auth/callback
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
