// Código Penal oficial SpainRP 2025
// Adaptado para entorno de rol, vigente desde 2025

const codigoPenal = {
    // Tráfico
    "1.1": { nombre: "Uso excesivo del claxon", multa: 100, tipo: "Multa" },
    "1.2": { nombre: "Giro indebido", multa: 125, tipo: "Multa" },
    "1.3": { nombre: "Circular en sentido contrario", multa: 1950, tipo: "Multa" },
    "1.4": { nombre: "Estacionar en zonas no habilitadas y obstruir la circulación", multa: 225, tipo: "Multa" },
    "1.5": { nombre: "Ignorar las señales de tráfico", multa: 275, tipo: "Multa" },
    "1.6": { nombre: "Saltarse un semáforo", multa: 550, tipo: "Multa" },
    "1.7": { nombre: "No ceder el paso a vehículos de emergencia", multa: 990, tipo: "Multa" },
    "1.8": { nombre: "Adelantamiento indebido", multa: 150, tipo: "Multa" },
    "1.9": { nombre: "Ignorar las señales de un policía de tránsito", multa: 500, tipo: "Multa+Arresto", prision: 1 },
    "1.10": { nombre: "Saltarse un control de tráfico", multa: 1000, tipo: "Multa+Arresto", prision: 3 },
    "1.11": { nombre: "Conducir un vehículo en malas condiciones", multa: 1150, tipo: "Multa" },
    "1.12": { nombre: "Exceso de velocidad permitido en la vía", multa: 300, tipo: "Multa" },
    "1.13": { nombre: "Conducción temeraria", multa: 300, tipo: "Multa" },
    "1.14": { nombre: "Conducir bajo los efectos de drogas o alcohol", multa: 750, tipo: "Multa" },
    "1.15": { nombre: "Iniciar una persecución", multa: 2500, tipo: "Multa+Arresto", prision: 7 },
    "1.16": { nombre: "Provocar un accidente con / o sin fuga", multa: 3500, tipo: "Multa+Arresto", prision: 5 },
    "1.17": { nombre: "No colocar los faros en la noche", multa: 250, tipo: "Multa" },
    "1.18": { nombre: "No usar intermitentes", multa: 275, tipo: "Multa" },
    "1.19": { nombre: "Negarse a la inspección del vehículo", multa: 225, tipo: "Multa" },
    "1.20": { nombre: "Circular con cualquier vehículo de granja por vías urbanas", multa: 750, tipo: "Multa" },
    "1.21": { nombre: "Circular a muy baja velocidad en una autopista", multa: 300, tipo: "Multa" },
    "1.22": { nombre: "Participar en carreras ilegales", multa: 2000, tipo: "Multa+Arresto", prision: 24 },
    "1.23": { nombre: "Provocar un accidente debido a una carrera ilegal", multa: 2700, tipo: "Multa+Arresto", prision: 48 },
    "1.24": { nombre: "Causar una muerte durante una carrera ilegal (CK)", multa: 12999, tipo: "Multa+CK", prision: "Cadena perpetua" },
    "1.25": { nombre: "Atropellar a alguien y darse a la fuga", multa: 3500, tipo: "Multa+Arresto", prision: 72 },
    "1.26": { nombre: "Atropellar a alguien y causarle daños psicológicos", multa: 0, tipo: "Multa" },
    "1.27": { nombre: "Circular sin el carnet de conducción tipo A", multa: 2000, tipo: "Multa" },
    "1.28": { nombre: "Circular sin el carnet correspondiente para vehículos motorizados tipo B", multa: 1000, tipo: "Multa" },
    "1.29": { nombre: "Circular con el carnet de conducir caducado", multa: 200, tipo: "Multa" },
    "1.30": { nombre: "Circular sin la ITV correspondiente", multa: 500, tipo: "Multa" },
    // Conductas erróneas, Agresiones y Disturbios
    "2.1": { nombre: "Alteración del orden público", multa: 500, tipo: "Multa" },
    "2.2": { nombre: "Racismo / Xenofobia", multa: 800, tipo: "Multa" },
    "2.3": { nombre: "Faltas de respeto a otro civil o funcionario", multa: 500, tipo: "Multa" },
    "2.4": { nombre: "Dañar mobiliario urbano", multa: 500, tipo: "Multa" },
    "2.5": { nombre: "Intento de violación", multa: 4450, tipo: "Multa+Arresto", prision: 8 },
    "2.6": { nombre: "Violación", multa: 22500, tipo: "Multa+Arresto", prision: 22 },
    "2.7": { nombre: "Amenaza de muerte a un civil", multa: 4000, tipo: "Multa" },
    "2.8": { nombre: "Acoso sexual (verbal o físico)", multa: 5500, tipo: "Multa" },
    "2.9": { nombre: "Uso indebido de máscara sin justificación", multa: 1500, tipo: "Multa" },
    "2.10": { nombre: "Circular desnudo o semidesnudo en vía pública", multa: 700, tipo: "Multa" },
    "2.11": { nombre: "Provocar peleas en vía pública", multa: 1000, tipo: "Multa+Arresto", prision: 1 },
    "2.12": { nombre: "Insultos o amenazas graves", multa: 1500, tipo: "Multa" },
    "2.13": { nombre: "Disturbios en eventos oficiales", multa: 2000, tipo: "Multa+Arresto", prision: 2 },
    "2.14": { nombre: "Uso indebido de pirotecnia", multa: 500, tipo: "Multa" },
    "2.15": { nombre: "Arrojar basura en la vía pública", multa: 200, tipo: "Multa" },
    "2.16": { nombre: "Ruidos molestos en zonas residenciales", multa: 300, tipo: "Multa" },
    "2.17": { nombre: "Incumplimiento de normativas de eventos", multa: 1000, tipo: "Multa" },
    "2.18": { nombre: "Obstrucción a la autoridad", multa: 2500, tipo: "Multa+Arresto", prision: 1 },
    "2.19": { nombre: "Falsas denuncias o acusaciones", multa: 2000, tipo: "Multa+Arresto", prision: 1 },
    "2.20": { nombre: "Suplantación de identidad", multa: 3000, tipo: "Multa+Arresto", prision: 2 },
    "2.21": { nombre: "Actos obscenos en público", multa: 1200, tipo: "Multa" },
    "2.22": { nombre: "Escándalo público", multa: 800, tipo: "Multa" },
    "2.23": { nombre: "Lenguaje ofensivo en espacios públicos", multa: 400, tipo: "Multa" },
    "2.24": { nombre: "Negarse a identificarse ante autoridades", multa: 1500, tipo: "Multa" },
    "2.25": { nombre: "Obstaculizar el tráfico sin motivo", multa: 1000, tipo: "Multa" },
    "2.26": { nombre: "Intento de soborno a funcionario", multa: 5000, tipo: "Multa+Arresto", prision: 3 },
    "2.27": { nombre: "Reuniones clandestinas con fines delictivos", multa: 4000, tipo: "Multa+Arresto", prision: 2 },
    "2.28": { nombre: "Uso de disfraces para delinquir o confundir", multa: 2500, tipo: "Multa" },
    "2.29": { nombre: "Fotografiar o grabar sin consentimiento", multa: 750, tipo: "Multa" },
    "2.30": { nombre: "Negarse a pagar servicios prestados", multa: 1000, tipo: "Multa" },
    // Estupefacientes
    "3.1": { nombre: "Posesión de drogas en pequeñas cantidades", multa: 1000, tipo: "Multa" },
    "3.2": { nombre: "Posesión de drogas en grandes cantidades", multa: 2000, tipo: "Multa+Arresto", prision: 24 },
    "3.3": { nombre: "Tráfico de drogas", multa: 3000, tipo: "Multa+Arresto", prision: 24 },
    "3.4": { nombre: "Consumo de drogas en espacios públicos", multa: 800, tipo: "Multa" },
    "3.5": { nombre: "Venta de drogas a menores", multa: 5000, tipo: "Multa+Arresto", prision: 4 },
    "3.6": { nombre: "Fabricación de sustancias ilícitas", multa: 6000, tipo: "Multa+Arresto", prision: 6 },
    "3.7": { nombre: "Conducción bajo efectos de estupefacientes", multa: 3000, tipo: "Multa" },
    "3.8": { nombre: "Transportar drogas en vehículos públicos", multa: 2500, tipo: "Multa+Arresto", prision: 1 },
    "3.9": { nombre: "Pertenencia a cartel de drogas", multa: 7000, tipo: "Multa+Arresto", prision: 6 },
    "3.10": { nombre: "Tenencia de utensilios para el procesamiento de drogas", multa: 1500, tipo: "Multa" },
    "3.11": { nombre: "Venta ilegal de medicamentos controlados", multa: 3500, tipo: "Multa+Arresto", prision: 1 },
    "3.12": { nombre: "Cultivo ilegal de sustancias narcóticas", multa: 4500, tipo: "Multa+Arresto", prision: 2 },
    "3.13": { nombre: "Distribución de drogas en eventos públicos", multa: 5000, tipo: "Multa+Arresto", prision: 3 },
    "3.14": { nombre: "Poseer laboratorio clandestino de drogas", multa: 10000, tipo: "Multa+Arresto", prision: 12 },
    "3.15": { nombre: "Introducción de drogas en prisión", multa: 6000, tipo: "Multa+Arresto", prision: 4 },
    "3.16": { nombre: "Financiamiento de operaciones relacionadas con drogas", multa: 7500, tipo: "Multa+Arresto", prision: 5 },
    "3.17": { nombre: "Utilizar menores para el transporte o venta de drogas", multa: 8000, tipo: "Multa+Arresto", prision: 6 },
    "3.18": { nombre: "Publicidad o incitación al consumo de drogas", multa: 2000, tipo: "Multa" },
    // Armas de fuego y tráfico
    "4.1": { nombre: "Posesión de arma sin licencia", multa: 2500, tipo: "Multa+Arresto", prision: 1 },
    "4.2": { nombre: "Venta ilegal de armas", multa: 5000, tipo: "Multa+Arresto", prision: 3 },
    "4.3": { nombre: "Uso de armas en vía pública sin justificación", multa: 3500, tipo: "Multa+Arresto", prision: 2 },
    "4.4": { nombre: "Modificación ilegal de armas", multa: 4000, tipo: "Multa+Arresto", prision: 3 },
    "4.5": { nombre: "Contrabando de armas", multa: 7000, tipo: "Multa+Arresto", prision: 6 },
    "4.6": { nombre: "Amenazar a un ciudadano con un arma", multa: 3000, tipo: "Multa+Arresto", prision: 2 },
    "4.7": { nombre: "Portar arma de guerra", multa: 10000, tipo: "Multa+Arresto", prision: 6 },
    "4.8": { nombre: "Disparos injustificados en vía pública", multa: 5000, tipo: "Multa+Arresto", prision: 3 },
    "4.9": { nombre: "Portar Beretta M9 con licencia pero fuera de normativa", multa: 2500, tipo: "Multa" },
    "4.10": { nombre: "Portar Colt M1911 sin licencia", multa: 2500, tipo: "Multa" },
    "4.11": { nombre: "Portar una TEC-9", multa: 4000, tipo: "Multa" },
    "4.12": { nombre: "Portar una AK-47", multa: 18000, tipo: "Multa+Arresto", prision: 24 },
    "4.13": { nombre: "Portar LMT-L129A1", multa: 10000, tipo: "Multa+Arresto", prision: 24 },
    "4.14": { nombre: "Portar objeto punzante con hoja de más de 13 cm", multa: 1000, tipo: "Multa" },
    "4.15": { nombre: "Venta de munición sin licencia", multa: 2000, tipo: "Multa" },
    "4.16": { nombre: "Fabricación casera de armas", multa: 6500, tipo: "Multa+Arresto", prision: 4 },
    "4.17": { nombre: "Amenazar a funcionarios con armas", multa: 4500, tipo: "Multa+Arresto", prision: 3 },
    "4.18": { nombre: "Uso de armas en eventos públicos o zonas seguras", multa: 8000, tipo: "Multa+Arresto", prision: 5 },
    "4.19": { nombre: "Portar armas en edificios gubernamentales sin autorización", multa: 7000, tipo: "Multa+Arresto", prision: 4 },
    "4.20": { nombre: "Utilizar armas para intimidar durante robos", multa: 10000, tipo: "Multa+Arresto", prision: 12 },
    // Homicidio y Agresiones
    "5.1": { nombre: "Agresión a civil", multa: 2000, tipo: "Multa+Arresto", prision: 12 },
    "5.2": { nombre: "Robo a civil", multa: 3500, tipo: "Multa+Arresto", prision: 15 },
    "5.3": { nombre: "Robo de vehículo", multa: 1500, tipo: "Multa+Arresto", prision: 6 },
    "5.4": { nombre: "Allanamiento de propiedad privada", multa: 3250, tipo: "Multa+Arresto", prision: 12 },
    "5.5": { nombre: "Detención policial ilegal", multa: 4000, tipo: "Multa" },
    "5.6": { nombre: "Secuestro", multa: 5000, tipo: "Multa+Arresto", prision: 24 },
    "5.7": { nombre: "Tentativa de secuestro", multa: 2500, tipo: "Multa+Arresto", prision: 12 },
    "5.8": { nombre: "Homicidio en grado de tentativa", multa: 7000, tipo: "Multa+Arresto", prision: 24 },
    "5.9": { nombre: "Homicidio", multa: 18000, tipo: "Multa+Arresto", prision: 30 },
    "5.10": { nombre: "Homicidio imprudente", multa: 12500, tipo: "Multa+Arresto", prision: 24 },
    "5.11": { nombre: "Asesinato", multa: 20000, tipo: "Multa+Arresto", prision: 124 },
    "5.12": { nombre: "Trata de personas", multa: 17500, tipo: "Multa+Arresto", prision: 30 },
    "5.13": { nombre: "Amenaza a un civil", multa: 2000, tipo: "Multa" },
    "5.14": { nombre: "Amenaza a un civil con arma blanca", multa: 2000, tipo: "Multa+Arresto", prision: 2 },
    "5.15": { nombre: "Violación de una orden judicial", multa: 1000, tipo: "Multa+Arresto", prision: 24 },
    "5.16": { nombre: "Estafa o fraude", multa: 2500, tipo: "Multa+Arresto", prision: 12 },
    "5.17": { nombre: "Destrucción de pruebas", multa: 1500, tipo: "Multa+Arresto", prision: 6 },
    "5.18": { nombre: "Soborno a funcionario", multa: 3000, tipo: "Multa+Arresto", prision: 4 },
    "5.19": { nombre: "Ultraje a símbolo nacional", multa: 800, tipo: "Multa" },
    "5.20": { nombre: "Sabotaje de infraestructura pública", multa: 5000, tipo: "Multa+Arresto", prision: 18 },
    // Delitos contra la administración pública
    "6.1": { nombre: "Violación de una orden judicial", multa: 1000, tipo: "Multa+Arresto", prision: 30 },
    "6.2": { nombre: "Obstrucción a la justicia", multa: 2500, tipo: "Multa+Arresto", prision: 9 },
    "6.3": { nombre: "Resistencia a la autoridad", multa: 2500, tipo: "Multa+Arresto", prision: 6 },
    "6.4": { nombre: "Negación a identificarse ante un funcionario", multa: 1000, tipo: "Multa+Arresto", prision: 9 },
    "6.5": { nombre: "Negación a presentar licencias a un funcionario", multa: 750, tipo: "Multa+Arresto", prision: 6 },
    "6.6": { nombre: "Distribución de material confidencial del Estado", multa: 1500, tipo: "Multa+Arresto", prision: 12 },
    "6.7": { nombre: "Soborno a funcionario público", multa: 5000, tipo: "Multa+Arresto", prision: 24 },
    "6.8": { nombre: "Desacato a la autoridad", multa: 2500, tipo: "Multa+Arresto", prision: 12 },
    "6.9": { nombre: "Malversación de fondos estatales", multa: 25000, tipo: "Multa+Arresto", prision: 24 },
    "6.10": { nombre: "Detención ilegal por parte de un funcionario", multa: 4000, tipo: "Multa" },
    "6.11": { nombre: "Amenaza a funcionario público", multa: 3000, tipo: "Multa+Arresto", prision: 12 },
    "6.12": { nombre: "Agresión a funcionario público", multa: 5000, tipo: "Multa+Arresto", prision: 18 },
    "6.13": { nombre: "Secuestro de funcionario público", multa: 10000, tipo: "Multa+Arresto", prision: 36 },
    "6.14": { nombre: "Tentativa de homicidio a funcionario público", multa: 15000, tipo: "Multa+Arresto", prision: 40 },
    "6.15": { nombre: "Homicidio de funcionario público", multa: 25000, tipo: "Multa+Arresto", prision: 420 },
    "6.16": { nombre: "Asesinato de funcionario público", multa: 35000, tipo: "Multa+Cadena Perpetua", prision: "Cadena perpetua" },
    "6.17": { nombre: "Falsificación de documentación oficial", multa: 2000, tipo: "Multa+Arresto", prision: 12 },
    "6.18": { nombre: "Uso indebido de bienes o fondos públicos", multa: 1500, tipo: "Multa+Arresto", prision: 6 },
    // Robos menores y mayores
    "7.1": { nombre: "Hurto (robo sin violencia)", multa: 1500, tipo: "Multa+Arresto", prision: 6 },
    "7.2": { nombre: "Robo a civil con violencia", multa: 3500, tipo: "Multa+Arresto", prision: 15 },
    "7.3": { nombre: "Robo de vehículo", multa: 2500, tipo: "Multa+Arresto", prision: 12 },
    "7.4": { nombre: "Robo de vehículo de alto valor", multa: 5000, tipo: "Multa+Arresto", prision: 18 },
    "7.5": { nombre: "Robo en establecimiento comercial", multa: 4000, tipo: "Multa+Arresto", prision: 15 },
    "7.6": { nombre: "Robo en institución pública o bancaria", multa: 7500, tipo: "Multa+Arresto", prision: 24 },
    "7.7": { nombre: "Robo con uso de arma de fuego", multa: 8000, tipo: "Multa+Arresto", prision: 30 },
    "7.8": { nombre: "Robo con secuestro o toma de rehenes", multa: 15000, tipo: "Multa+Arresto", prision: 36 },
    "7.9": { nombre: "Robo en vivienda privada", multa: 5000, tipo: "Multa+Arresto", prision: 18 },
    "7.10": { nombre: "Uso de inhibidores de señal para robo y drones", multa: 6000, tipo: "Multa+Arresto", prision: 24 },
    "7.11": { nombre: "Posesión de herramientas de robo sin justificación", multa: 3000, tipo: "Multa+Arresto", prision: 12 },
    "7.12": { nombre: "Robos mayores (Banco, Joyería)", multa: 15000, tipo: "Multa+Arresto", prision: 20 },
    "7.13": { nombre: "Arrebato (robo en vía pública sin fuerza directa)", multa: 1000, tipo: "Multa+Arresto", prision: 4 },
    "7.14": { nombre: "Robo con uso de explosivos o fuerza especial", multa: 10000, tipo: "Multa+Arresto", prision: 30 },
    "7.15": { nombre: "Robo de bienes culturales o de patrimonio", multa: 12000, tipo: "Multa+Arresto", prision: 36 },
    // Bandas y Organizaciones criminales
    "8.1": { nombre: "Pertenencia a una banda criminal", multa: 7500, tipo: "Multa+Arresto", prision: 48 },
    "8.2": { nombre: "Creación de una banda criminal (Jefe)", multa: 0, tipo: "Cadena perpetua", prision: "Cadena perpetua" },
    "8.3": { nombre: "Financiamiento de una organización criminal", multa: 12500, tipo: "Multa+Arresto", prision: 60 },
    "8.4": { nombre: "Colaboración con banda criminal", multa: 5000, tipo: "Multa+Arresto", prision: 36 },
    "8.5": { nombre: "Asociación para delinquir (Pandilla)", multa: 6000, tipo: "Multa+Arresto", prision: 24 },
    "8.6": { nombre: "Uso de violencia para control territorial", multa: 9000, tipo: "Multa+Arresto", prision: 60 },
    "8.7": { nombre: "Extorsión organizada", multa: 10000, tipo: "Multa+Arresto", prision: 60 },
    "8.8": { nombre: "Atentado contra entidad pública o policial", multa: 15000, tipo: "Multa+Arresto", prision: 96 },
    "8.9": { nombre: "Secuestro organizado", multa: 20000, tipo: "Multa+Arresto", prision: 120 },
    "8.10": { nombre: "Tráfico de armas organizado", multa: 18000, tipo: "Multa+Arresto", prision: 72 },
    "8.11": { nombre: "Tráfico de drogas organizado", multa: 20000, tipo: "Multa+Arresto", prision: 144 },
    "8.12": { nombre: "Lavado de dinero para una organización criminal", multa: 25000, tipo: "Multa+Arresto", prision: 72 },
    "8.13": { nombre: "Conspiración criminal transnacional", multa: 22000, tipo: "Multa+Arresto", prision: 72 },
    "8.14": { nombre: "Tráfico de seres humanos organizado", multa: 30000, tipo: "Multa+Arresto", prision: 180 },
    "8.15": { nombre: "Corrupción de funcionario público en beneficio de organización criminal", multa: 14000, tipo: "Multa+Arresto", prision: 36 },
    "8.16": { nombre: "Fraude informático organizado (cibercrimen)", multa: 12000, tipo: "Multa+Arresto", prision: 24 },
    // Falsificación de Documentos
    "9.1": { nombre: "Falsificación de documento público", multa: 7500, tipo: "Multa+Arresto", prision: 24 },
    "9.2": { nombre: "Falsificación de documento privado", multa: 5000, tipo: "Multa+Arresto", prision: 18 },
    "9.3": { nombre: "Uso de documento falso", multa: 4000, tipo: "Multa+Arresto", prision: 12 },
    "9.4": { nombre: "Alteración de información en documentos oficiales", multa: 6000, tipo: "Multa+Arresto", prision: 24 },
    "9.5": { nombre: "Falsificación de firmas", multa: 5500, tipo: "Multa+Arresto", prision: 18 },
    "9.6": { nombre: "Uso de identidad falsa", multa: 7000, tipo: "Multa+Arresto", prision: 30 },
    "9.7": { nombre: "Suplantación de identidad de un ciudadano", multa: 8000, tipo: "Multa+Arresto", prision: 36 },
    "9.8": { nombre: "Suplantación de identidad de un funcionario público", multa: 10000, tipo: "Multa+Arresto", prision: 42 },
    "9.9": { nombre: "Falsificación de licencias o permisos oficiales", multa: 8500, tipo: "Multa+Arresto", prision: 36 },
    "9.10": { nombre: "Producción o distribución de documentos falsos", multa: 12000, tipo: "Multa+Arresto", prision: 48 },
    // Suplantación de Identidad
    "10.1": { nombre: "Suplantación de identidad de ciudadano común", multa: 7000, tipo: "Multa+Arresto", prision: 24 },
    "10.2": { nombre: "Suplantación de identidad de funcionario público", multa: 10000, tipo: "Multa+Arresto", prision: 36 },
    "10.3": { nombre: "Suplantación de identidad de miembro de fuerzas de seguridad", multa: 12000, tipo: "Multa+Arresto", prision: 42 },
    "10.4": { nombre: "Suplantación de identidad para cometer fraude financiero", multa: 15000, tipo: "Multa+Arresto", prision: 48 },
    "10.5": { nombre: "Uso de identidad robada para acceder a sistemas restringidos", multa: 13000, tipo: "Multa+Arresto", prision: 42 },
    "10.6": { nombre: "Venta o transferencia de identidades falsas", multa: 14000, tipo: "Multa+Arresto", prision: 48 },
    "10.7": { nombre: "Suplantación de identidad en redes sociales con fines delictivos", multa: 6000, tipo: "Multa+Arresto", prision: 18 },
    "10.8": { nombre: "Creación y uso de múltiples identidades falsas", multa: 16000, tipo: "Multa+Arresto", prision: 54 },
    "10.9": { nombre: "Suplantación de identidad de figura pública o celebridad para cometer delitos", multa: 11000, tipo: "Multa+Arresto", prision: 36 },
    // Atentados contra la Naturaleza
    "11.1": { nombre: "Suelta o vertido ilegal de residuos tóxicos en ecosistemas naturales", multa: 20000, tipo: "Multa+Arresto", prision: 60 },
    "11.2": { nombre: "Tala ilegal de árboles en áreas protegidas", multa: 12000, tipo: "Multa+Arresto", prision: 36 },
    "11.3": { nombre: "Caza o pesca de especies en peligro de extinción", multa: 15000, tipo: "Multa+Arresto", prision: 48 },
    "11.4": { nombre: "Incendio forestal provocado", multa: 25000, tipo: "Multa+Arresto", prision: 72 },
    "11.5": { nombre: "Contaminación de fuentes de agua", multa: 18000, tipo: "Multa+Arresto", prision: 54 },
    "11.6": { nombre: "Construcción ilegal en zonas protegidas o reservas naturales", multa: 17000, tipo: "Multa+Arresto", prision: 42 },
    "11.7": { nombre: "Tráfico de flora o fauna protegida", multa: 16000, tipo: "Multa+Arresto", prision: 48 },
    "11.8": { nombre: "Uso de productos químicos prohibidos en actividades agrícolas", multa: 14000, tipo: "Multa+Arresto", prision: 36 },
    "11.9": { nombre: "Destrucción de hábitats naturales con maquinaria pesada sin autorización", multa: 19000, tipo: "Multa+Arresto", prision: 60 },
    "11.10": { nombre: "Entrar al Parque Natural de High Rock sin permiso", multa: 13000, tipo: "Multa+Arresto", prision: 36 },
    "11.11": { nombre: "Encubrimiento de delitos ecológicos por parte de funcionarios públicos", multa: 22000, tipo: "Multa+Arresto", prision: 60 },
    "11.12": { nombre: "Reincidencia en delitos ambientales", multa: 0, tipo: "Multa+Arresto", prision: 12 },
};

export default codigoPenal;
